import { Bot, Check, CloudCog, DatabaseZap, FileScan, Gauge, LayoutDashboard, LockKeyhole, Network, RefreshCw, SearchCheck, ShieldCheck, Sparkles, TimerReset, Workflow } from "lucide-react"

const areas = [
  { number: "01", label: "Portal Automation", title: "Faster, More Consistent Payer Data Retrieval", description: "Our portal automation solutions retrieve eligibility, claim status, and other payer information directly from insurance portals, reducing dependency on repetitive manual lookups.", benefits: ["Consistent and accurate data retrieval across payer portals", "Faster eligibility and claim status verification", "Reduced manual effort and data-entry errors", "Improved productivity and turnaround time"], icon: CloudCog, accent: "from-cyan-500 to-blue-600", wash: "from-cyan-50 to-blue-50" },
  { number: "02", label: "Audit Automation", title: "Automated Controls for Greater Accuracy", description: "Our audit automation solutions cross-verify production, charge, and billing data across multiple sources to identify discrepancies early and strengthen operational controls.", benefits: ["Automated validation across multiple data sources", "Early identification of billing and production discrepancies", "Reduced manual audit effort", "Improved data accuracy and process compliance"], icon: SearchCheck, accent: "from-violet-500 to-indigo-600", wash: "from-violet-50 to-indigo-50" },
  { number: "03", label: "Document Processing Automation", title: "Transforming Documents into Actionable Data", description: "AI-assisted document processing extracts relevant information from patient records, EOBs, PDFs, scanned documents, and coding-related documentation, converting unstructured information into standardized, usable data.", benefits: ["Automated extraction from PDF and scanned documents", "Reduced manual data entry", "Standardized and structured output", "Faster document processing and turnaround time"], icon: FileScan, accent: "from-amber-400 to-orange-500", wash: "from-amber-50 to-orange-50" },
  { number: "04", label: "Reporting & Workflow Automation", title: "Reliable Reporting Without the Manual Overhead", description: "Our reporting automation solutions generate recurring operational reports—including rejection, productivity, reconciliation, and other management reports—according to predefined schedules, with each process tracked for completion and exceptions.", benefits: ["Automated report generation on defined schedules", "Reduced dependency on manual reporting", "Visibility into report status and completion", "Early identification of processing failures or exceptions"], icon: Workflow, accent: "from-emerald-400 to-teal-600", wash: "from-emerald-50 to-teal-50" },
]

const capabilities = [
  [LayoutDashboard, "Centralized dashboards for call center, audit, and organizational performance"],
  [Network, "Workforce, attendance, and resource management with role-based access"],
  [RefreshCw, "SharePoint and mailbox backup and recovery capabilities"],
  [DatabaseZap, "Vendor invoice management and client query tracking"],
  [Gauge, "Centralized operational data and performance visibility"],
]

const AboutTechnology = () => <>
  <section className="relative isolate overflow-hidden bg-[#092f42] text-white">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(34,211,238,.22),transparent_28%),radial-gradient(circle_at_88%_22%,rgba(250,204,21,.18),transparent_24%),linear-gradient(125deg,#092f42_0%,#0b5268_54%,#123b50_100%)]" />
    <div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.12)_1px,transparent_1px)] [background-size:48px_48px]" />
    <div className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 py-20 lg:grid-cols-[1.08fr_.92fr] lg:py-24">
      <div className="reveal">
        <div className="inline-flex items-center gap-2 rounded-full border border-cyan-200/30 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.24em] text-cyan-100"><Sparkles className="h-4 w-4 text-amber-300" /> Technology & Automation</div>
        <h1 className="mt-6 font-heading text-4xl font-bold leading-[1.08] md:text-5xl">Automation Engineered for <span className="text-cyan-300">Accuracy</span>, Speed, and Compliance.</h1>
        <p className="mt-6 text-lg leading-relaxed text-slate-200">Opus BPO integrates automation across the revenue cycle to reduce manual effort, minimize errors, and accelerate turnaround time — without compromising HIPAA-aligned data handling standards.</p>
        <div className="mt-8 flex flex-wrap gap-3">{["Fewer manual steps", "Faster turnaround", "Stronger controls"].map(x => <span key={x} className="flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-semibold"><Check className="h-4 w-4 text-amber-300" />{x}</span>)}</div>
      </div>
      <div className="relative grid grid-cols-2 gap-4" aria-label="Connected revenue cycle automation infographic">
        {[ [Bot,"Automation"], [TimerReset,"Speed"], [SearchCheck,"Accuracy"], [ShieldCheck,"Compliance"] ].map(([Icon,label],i) => <div key={label} className={`flex min-h-36 flex-col items-center justify-center rounded-[28px] border border-white/20 bg-white/10 p-5 shadow-2xl backdrop-blur ${i%2 ? "translate-y-6" : ""}`}><span className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-cyan-300 to-blue-500"><Icon className="h-7 w-7" /></span><span className="mt-4 font-semibold">{label}</span></div>)}
      </div>
    </div>
  </section>

  <section className="section-divider bg-white"><div className="mx-auto max-w-6xl px-6 py-20">
    <div className="mx-auto max-w-5xl text-center reveal"><p className="text-sm font-semibold uppercase tracking-[.22em] text-brand-blue">How Our Automation Works</p><h2 className="mt-4 font-heading text-3xl font-semibold text-brand-slate md:text-4xl">Connected workflows. Clearer decisions. Stronger control.</h2><p className="mx-auto mt-5 max-w-4xl text-lg font-medium leading-relaxed text-slate-700">Every solution follows a practical operating model: capture reliable inputs, validate them against defined rules, route exceptions to the right teams, and make performance visible. The result is automation that fits into existing operations instead of adding another layer of complexity.</p><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["01","Capture","Reliable data inputs"],["02","Validate","Rule-based quality checks"],["03","Route","Exceptions to the right team"],["04","Report","Clear operational visibility"]].map(([number,title,detail]) => <div key={title} className="relative overflow-hidden rounded-2xl border border-slate-200 bg-slate-50 px-5 py-5 text-left"><span className="absolute right-3 top-1 font-heading text-4xl font-bold text-brand-blue/10">{number}</span><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-blue">{title}</p><p className="mt-2 text-sm font-medium text-slate-600">{detail}</p></div>)}</div></div>
    <div className="mt-16 space-y-8">{areas.map(({number,label,title,description,benefits,icon:Icon,accent,wash}) => <article key={number} className={`reveal relative grid overflow-hidden rounded-[30px] border border-slate-200 bg-gradient-to-br ${wash} shadow-[0_24px_60px_-42px_rgba(15,23,42,.5)] lg:grid-cols-[.76fr_1.24fr]`}>
      <div className="relative p-7 md:p-9"><div className={`absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${accent}`} /><span className="absolute -right-3 -top-7 font-heading text-[8rem] font-bold text-slate-900/[.045]">{number}</span><span className={`inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br ${accent} text-white shadow-lg`}><Icon className="h-7 w-7" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.22em] text-slate-500">{number} | {label}</p><h3 className="mt-3 font-heading text-2xl font-semibold text-brand-slate">{title}</h3><p className="mt-5 text-sm font-medium leading-relaxed text-slate-600">{description}</p></div>
      <div className="border-t border-white/80 bg-white/75 p-7 md:p-9 lg:border-l lg:border-t-0"><p className="text-xs font-bold uppercase tracking-[.22em] text-brand-blue">Key Benefits</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{benefits.map(b => <div key={b} className="flex items-start gap-3 rounded-2xl border border-white bg-white/80 p-4 shadow-sm"><span className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-gradient-to-br ${accent}`}><Check className="h-3.5 w-3.5 text-white" /></span><p className="text-sm font-medium leading-relaxed text-slate-700">{b}</p></div>)}</div></div>
    </article>)}</div>
  </div></section>

  <section className="section-divider bg-[linear-gradient(135deg,#eef9fc,#f6f3ff_50%,#fff8e7)]"><div className="mx-auto grid max-w-6xl items-center gap-12 px-6 py-20 lg:grid-cols-[.92fr_1.08fr]">
    <div className="relative reveal"><div className="overflow-hidden rounded-[34px] border-8 border-white shadow-2xl"><img src="/aboutwhy-24.png" alt="Operational technology and reporting dashboard" className="h-[430px] w-full object-cover" /></div><div className="absolute -bottom-6 right-0 max-w-[250px] rounded-3xl bg-[#0c5268] p-5 text-white shadow-xl"><LayoutDashboard className="h-7 w-7 text-amber-300" /><p className="mt-3 text-sm font-semibold">One connected view across operations, workforce, and governance.</p></div></div>
    <div className="reveal"><p className="text-sm font-semibold uppercase tracking-[.22em] text-brand-blue">05 | Operational Dashboards & Internal Platforms</p><h2 className="mt-4 font-heading text-3xl font-semibold text-brand-slate md:text-4xl">Purpose-Built Technology for Smarter Operations</h2><p className="mt-5 font-medium leading-relaxed text-slate-700">Beyond process automation, Opus BPO has developed purpose-built internal applications and dashboards to support <strong>revenue cycle operations, workforce management, performance monitoring, and data governance</strong> across the organization.</p><p className="mt-7 text-xs font-bold uppercase tracking-[.22em] text-slate-500">Key Capabilities</p><div className="mt-4 space-y-3">{capabilities.map(([Icon,text]) => <div key={text} className="flex items-center gap-4 rounded-2xl border border-white bg-white/80 p-4 shadow-sm"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-cyan-500 to-blue-600 text-white"><Icon className="h-5 w-5" /></span><p className="text-sm font-medium text-slate-700">{text}</p></div>)}</div></div>
  </div></section>

  <section className="section-divider bg-white"><div className="mx-auto max-w-6xl px-6 py-20"><div className="relative overflow-hidden rounded-[36px] bg-[linear-gradient(120deg,#092f42,#0d6074)] px-7 py-14 text-white shadow-2xl md:px-14"><div className="relative grid items-center gap-10 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-3"><LockKeyhole className="h-6 w-6 text-amber-300" /><p className="text-xs font-bold uppercase tracking-[.24em] text-cyan-100">People + Technology</p></div><h2 className="mt-4 font-heading text-3xl font-semibold md:text-4xl">Automation That Works With Your Operations</h2><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-200">At Opus BPO, automation is not about replacing people—it is about <strong className="text-white">eliminating repetitive work, strengthening controls, and enabling teams to focus on higher-value activities</strong>.</p><p className="mt-4 max-w-3xl leading-relaxed text-slate-300">Our automation solutions are developed and maintained with the same focus on <strong className="text-white">data security, confidentiality, compliance, and operational integrity</strong> that governs our client operations.</p></div><div className="grid h-32 w-32 place-items-center rounded-full border border-white/20 bg-white/10"><ShieldCheck className="h-14 w-14 text-cyan-300" /></div></div></div></div></section>
</>

export default AboutTechnology