import { useEffect, useState } from "react"
import { Bot, Check, CloudCog, DatabaseZap, FileScan, Gauge, LayoutDashboard, LockKeyhole, Network, RefreshCw, SearchCheck, ShieldCheck, Sparkles, TimerReset, Workflow } from "lucide-react"

const areas = [
  { number: "01", label: "Portal Automation", title: "Faster, More Consistent Payer Data Retrieval", description: "Our portal automation solutions retrieve eligibility, claim status, and other payer information directly from insurance portals, reducing dependency on repetitive manual lookups.", benefits: ["Consistent and accurate data retrieval across payer portals", "Faster eligibility and claim status verification", "Reduced manual effort and data-entry errors", "Improved productivity and turnaround time"], icon: CloudCog, accent: "from-cyan-500 to-blue-600", wash: "from-cyan-50 to-blue-50" },
  { number: "02", label: "Audit Automation", title: "Automated Controls for Greater Accuracy", description: "Our audit automation solutions cross-verify production, charge, and billing data across multiple sources to identify discrepancies early and strengthen operational controls.", benefits: ["Automated validation across multiple data sources", "Early identification of billing and production discrepancies", "Reduced manual audit effort", "Improved data accuracy and process compliance"], icon: SearchCheck, accent: "from-violet-500 to-indigo-600", wash: "from-violet-50 to-indigo-50" },
  { number: "03", label: "Document Processing Automation", title: "Transforming Documents into Actionable Data", description: "AI-assisted document processing extracts relevant information from patient records, EOBs, PDFs, scanned documents, and coding-related documentation, converting unstructured information into standardized, usable data.", benefits: ["Automated extraction from PDF and scanned documents", "Reduced manual data entry", "Standardized and structured output", "Faster document processing and turnaround time"], icon: FileScan, accent: "from-amber-400 to-orange-500", wash: "from-amber-50 to-orange-50" },
  { number: "04", label: "Reporting & Workflow Automation", title: "Reliable Reporting Without the Manual Overhead", description: "Our reporting automation solutions generate recurring operational reports—including rejection, productivity, reconciliation, and other management reports—according to predefined schedules, with each process tracked for completion and exceptions.", benefits: ["Automated report generation on defined schedules", "Reduced dependency on manual reporting", "Visibility into report status and completion", "Early identification of processing failures or exceptions"], icon: Workflow, accent: "from-emerald-400 to-teal-600", wash: "from-emerald-50 to-teal-50" },
  { number: "05", label: "Operational Dashboards & Internal Platforms", title: "Purpose-Built Technology for Smarter Operations", description: "Beyond process automation, Opus BPO has developed purpose-built internal applications and dashboards to support revenue cycle operations, workforce management, performance monitoring, and data governance across the organization.", benefits: ["Centralized dashboards for call center, audit, and organizational performance", "Workforce, attendance, and resource management with role-based access", "SharePoint and mailbox backup and recovery capabilities", "Vendor invoice management and client query tracking", "Centralized operational data and performance visibility"], icon: LayoutDashboard, accent: "from-blue-500 to-indigo-700", wash: "from-blue-50 to-indigo-50" },
]

const capabilities = [
  [LayoutDashboard, "Centralized dashboards for call center, audit, and organizational performance"],
  [Network, "Workforce, attendance, and resource management with role-based access"],
  [RefreshCw, "SharePoint and mailbox backup and recovery capabilities"],
  [DatabaseZap, "Vendor invoice management and client query tracking"],
  [Gauge, "Centralized operational data and performance visibility"],
]

const SceneVisual = ({ index, area }) => {
  const Icon = area.icon
  if (index === 0) return <div className="relative h-80"><CloudCog className="absolute left-1/2 top-1/2 h-32 w-32 -translate-x-1/2 -translate-y-1/2 text-cyan-500"/>{["Eligibility","Claim Status","Payer Data"].map((x,i)=><div key={x} className={`absolute ${i===0?'left-1/2 top-0 -translate-x-1/2':i===1?'bottom-4 left-8':'bottom-4 right-8'} text-center`}><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-white text-xl font-bold text-cyan-600 shadow-xl">{i+1}</span><p className="mt-3 text-xs font-bold uppercase tracking-wider text-slate-600">{x}</p></div>)}</div>
  if (index === 1) return <div className="relative h-80"><SearchCheck className="absolute left-1/2 top-1/2 z-10 h-28 w-28 -translate-x-1/2 -translate-y-1/2 text-violet-600"/><div className="absolute left-1/2 top-1/2 h-64 w-64 -translate-x-1/2 -translate-y-1/2 rounded-full border-[22px] border-violet-200/60"/><div className="absolute left-1/2 top-1/2 h-44 w-44 -translate-x-1/2 -translate-y-1/2 animate-pulse rounded-full border border-violet-400"/>{["Production","Charges","Billing","Verified"].map((x,i)=><span key={x} className={`absolute ${i===0?'left-0 top-8':i===1?'right-0 top-8':i===2?'bottom-4 left-0':'bottom-4 right-0'} text-xs font-bold uppercase tracking-wider text-violet-800`}>{x}</span>)}</div>
  if (index === 2) return <div className="flex h-80 items-center justify-center gap-5"><div className="text-center"><FileScan className="mx-auto h-24 w-24 text-orange-500"/><p className="mt-3 text-xs font-bold uppercase text-slate-600">Documents</p></div><span className="text-4xl text-orange-300">→</span><div className="text-center"><Bot className="mx-auto h-28 w-28 animate-pulse text-amber-500"/><p className="mt-3 text-xs font-bold uppercase text-slate-600">AI Extraction</p></div><span className="text-4xl text-orange-300">→</span><div className="text-center"><DatabaseZap className="mx-auto h-24 w-24 text-slate-800"/><p className="mt-3 text-xs font-bold uppercase text-slate-600">Structured Data</p></div></div>
  if (index === 3) return <div className="relative flex h-80 items-end justify-center gap-4 pb-10">{[42,68,54,84,72,96].map((height,i)=><span key={i} className="w-10 rounded-t-full bg-gradient-to-t from-emerald-600 to-cyan-300 shadow-lg transition-all duration-500 hover:-translate-y-3" style={{height:`${height}%`}}/>)}<Workflow className="absolute right-8 top-4 h-20 w-20 text-emerald-700"/><p className="absolute bottom-0 text-xs font-bold uppercase tracking-[.2em] text-emerald-800">Scheduled reporting flow</p></div>
  return <div className="relative grid h-80 grid-cols-2 place-content-center gap-5 px-10"><LayoutDashboard className="absolute left-1/2 top-1/2 h-28 w-28 -translate-x-1/2 -translate-y-1/2 text-blue-700"/>{[[Gauge,"Performance"],[Network,"Workforce"],[RefreshCw,"Recovery"],[DatabaseZap,"Data Governance"]].map(([NodeIcon,label],i)=><div key={label} className={`flex items-center gap-3 ${i%2?'justify-end text-right':''}`}><NodeIcon className="h-12 w-12 text-indigo-500"/><span className="max-w-24 text-xs font-bold uppercase text-slate-600">{label}</span></div>)}</div>
}

const AutomationEcosystem = () => {
  const [activeIndex, setActiveIndex] = useState(0)
  useEffect(() => {
    const nodes = areas.map((area) => document.getElementById(`automation-${area.number}`)).filter(Boolean)
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveIndex(Number(entry.target.dataset.index))), { rootMargin: "-40% 0px -40%", threshold: 0 })
    nodes.forEach((node) => observer.observe(node))
    return () => observer.disconnect()
  }, [])
  const active = areas[activeIndex]
  const ActiveIcon = active.icon
  return <section className="section-divider bg-[#f5f8f9]"><div className="mx-auto max-w-7xl px-6 py-20"><div className="mx-auto max-w-4xl text-center"><p className="text-sm font-semibold uppercase tracking-[.22em] text-brand-blue">Automation in Action</p><h2 className="mt-4 font-heading text-3xl font-semibold text-brand-slate md:text-4xl">A scroll-driven view of the connected revenue cycle.</h2></div>
    <div className="mt-16 grid items-start gap-12 lg:grid-cols-[.78fr_1.22fr]">
      <aside className="sticky top-40 hidden min-h-[620px] overflow-hidden bg-[#0b4358] px-10 py-12 text-white lg:flex lg:flex-col"><span className="absolute -right-8 top-4 font-heading text-[12rem] font-black leading-none text-white/[.05]">{active.number}</span><div className="relative"><span className={`grid h-16 w-16 place-items-center rounded-full bg-gradient-to-br ${active.accent}`}><ActiveIcon className="h-8 w-8"/></span><p className="mt-8 text-xs font-bold uppercase tracking-[.24em] text-cyan-200">{active.label}</p><h3 className="mt-5 font-heading text-4xl font-semibold leading-tight">{active.title}</h3><p className="mt-6 leading-relaxed text-slate-200">{active.description}</p></div><div className="relative mt-auto flex gap-2">{areas.map((area,index)=><button key={area.number} type="button" onClick={()=>document.getElementById(`automation-${area.number}`)?.scrollIntoView({behavior:'smooth'})} className={`h-2 flex-1 rounded-full transition ${index===activeIndex?'bg-amber-300':'bg-white/20 hover:bg-white/40'}`} aria-label={`Go to ${area.label}`}/>)}</div></aside>
      <div>{areas.map((area,index)=>{const Icon=area.icon;return <article id={`automation-${area.number}`} data-index={index} key={area.number} className="scroll-mt-36 flex min-h-[760px] flex-col justify-center py-20"><div className="lg:hidden"><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-blue">{area.number} · {area.label}</p><h3 className="mt-4 text-3xl font-semibold text-brand-slate">{area.title}</h3><p className="mt-4 text-slate-600">{area.description}</p></div><div className="relative mt-10 min-h-[360px]"><SceneVisual index={index} area={area}/></div><div className="mt-10 grid gap-x-10 gap-y-6 sm:grid-cols-2">{area.benefits.map((benefit,benefitIndex)=><div key={benefit} className="group flex items-start gap-4"><span className={`font-heading text-4xl font-black text-transparent bg-clip-text bg-gradient-to-br ${area.accent} transition group-hover:scale-110`}>0{benefitIndex+1}</span><div><span className={`block h-1 w-10 rounded-full bg-gradient-to-r ${area.accent}`}/><p className="mt-3 text-sm font-semibold leading-relaxed text-slate-700">{benefit}</p></div></div>)}</div></article>})}</div>
    </div>
  </div></section>
}
const AboutTechnology = () => <>
  <section className="relative isolate overflow-hidden bg-[#092f42] text-white">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(34,211,238,.22),transparent_28%),radial-gradient(circle_at_88%_22%,rgba(250,204,21,.18),transparent_24%),linear-gradient(125deg,#092f42_0%,#0b5268_54%,#123b50_100%)]" />
    <div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.12)_1px,transparent_1px)] [background-size:48px_48px]" />
    <div className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 py-20 lg:grid-cols-[1.08fr_.92fr] lg:py-24">
      <div className="reveal">
        <div className="inline-flex items-center gap-2 rounded-full border border-cyan-200/30 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.24em] text-cyan-100"><Sparkles className="h-4 w-4 text-amber-300" /> Technology & Automation</div>
        <h1 className="mt-6 font-heading text-4xl font-bold leading-[1.08] md:text-5xl">Automation Engineered for <span className="text-cyan-300">Accuracy</span>, Speed, and Compliance.</h1>
        <p className="mt-6 text-lg leading-relaxed text-slate-200">Opus BPO integrates automation across the revenue cycle to reduce manual effort, minimize errors, and accelerate turnaround time — without compromising HIPAA-aligned data handling standards.</p>
        <div className="mt-8 flex flex-wrap gap-3">{["Fewer manual steps", "Faster turnaround", "Stronger controls"].map(x => <span key={x} className="flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-semibold"><Check className="h-4 w-4 text-amber-300" />{x}</span>)}</div>
      </div>
      <div className="relative grid grid-cols-2 gap-4" aria-label="Connected revenue cycle automation infographic">
        {[ [Bot,"Automation"], [TimerReset,"Speed"], [SearchCheck,"Accuracy"], [ShieldCheck,"Compliance"] ].map(([Icon,label],i) => <div key={label} className={`flex min-h-36 flex-col items-center justify-center rounded-[28px] border border-white/20 bg-white/10 p-5 shadow-2xl backdrop-blur ${i%2 ? "translate-y-6" : ""}`}><span className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-cyan-300 to-blue-500"><Icon className="h-7 w-7" /></span><span className="mt-4 font-semibold">{label}</span></div>)}
      </div>
    </div>
  </section>

  <AutomationEcosystem />

  <section className="section-divider bg-white"><div className="mx-auto max-w-6xl px-6 py-20"><div className="relative overflow-hidden rounded-[36px] bg-[linear-gradient(120deg,#092f42,#0d6074)] px-7 py-14 text-white shadow-2xl md:px-14"><div className="relative grid items-center gap-10 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-3"><LockKeyhole className="h-6 w-6 text-amber-300" /><p className="text-xs font-bold uppercase tracking-[.24em] text-cyan-100">People + Technology</p></div><h2 className="mt-4 font-heading text-3xl font-semibold md:text-4xl">Automation That Works With Your Operations</h2><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-200">At Opus BPO, automation is not about replacing people—it is about <strong className="text-white">eliminating repetitive work, strengthening controls, and enabling teams to focus on higher-value activities</strong>.</p><p className="mt-4 max-w-3xl leading-relaxed text-slate-300">Our automation solutions are developed and maintained with the same focus on <strong className="text-white">data security, confidentiality, compliance, and operational integrity</strong> that governs our client operations.</p></div><div className="grid h-32 w-32 place-items-center rounded-full border border-white/20 bg-white/10"><ShieldCheck className="h-14 w-14 text-cyan-300" /></div></div></div></div></section>
</>

export default AboutTechnology